### ISSUE TITLE
不能运行

### ISSUE THREAD

**Issue by ryc787725121** [easemob/livestream_demo_ios#10]
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_UCloudGPUImageBeautyFilter", referenced from:
      objc-class-ref in FilterManager.o
  "_OBJC_CLASS_$_UCloudMediaPlayer", referenced from:
      objc-class-ref in PlayerManager.o
 什么情况，。这里类是存在的

**Comment by lizilong1989** [comment]
@ryc787725121 pod install之后, 运行编译没有发现你说的问题, xcode是什么版本,确定code是最新的吗?

**Comment by ryc787725121** [comment]
Xcode 8 ,下载了，2次，运行，都不行，都是这样，

**Comment by lizilong1989** [comment]
@ryc787725121 真机还是模拟器?我这边都没问题.你自己check一下项目中的libUCloudMediaPlayer.a, search path是否正确

**Comment by ryc787725121** [comment]
真机，大哥，要不你给我发一份吧， 787725121@qq.com 谢谢了。

**Comment by lizilong1989** [comment]
@ryc787725121 我就是直接就是从github clone下来的, 跟你那边应该没有任何区别.

**Comment by ryc787725121** [comment]
我也纳闷啊，一般都是git clone 下载，然后 pod install 就完事了。这个弄完，直接报16个上面的错误，我看下了，项目中的那些文件都存在的，

**Comment by lizilong1989** [comment]
@ryc787725121 15131968@qq.com, 也可以把你的项目给我发过来, 我帮你看看.

**Comment by ryc787725121** [comment]
已经发过去了，查看下吧，谢谢；

**Comment by lizilong1989** [comment]
@ryc787725121 你说的问题我看到了, 下载下来的libUCloudMediaRecorder.a,libUCloudMediaPlayer.a这两个lib只有133字节,我不知道是github的问题,还是最近有什么改动,不过git clone下来应该是没有问题的.先不要用download zip.具体原因我在查一查

**Comment by ryc787725121** [comment]
恩恩，好的，麻烦给我发一个可以运行的demo .787725121@qq.com .谢谢

**Comment by lizilong1989** [comment]
@ryc787725121 已经发过去了
