### ISSUE TITLE
还是运行了.当前时间 2017.3.31

### ISSUE THREAD

**Issue by WangYng** [easemob/livestream_demo_ios#13]
Undefined symbols for architecture arm64:
"OBJC_CLASS$_UCloudGPUImageBeautyFilter", referenced from:
objc-class-ref in FilterManager.o
"OBJC_CLASS$_UCloudMediaPlayer", referenced from:
objc-class-ref in PlayerManager.o

**Comment by lizilong1989** [comment]
@WangYng 你选择branch是master吗？我测试时没有问题的

**Comment by WangYng** [comment]
@lizilong1989 我用的是HEAD分支

**Comment by lizilong1989** [comment]
@WangYng 你拉取一下最新的code再试一下

**Comment by WangYng** [comment]
@lizilong1989 lib目录下的文件大小还是异常的
192:lib wangyang$ du -a
16	./.DS_Store
8	./Player/libUCloudMediaPlayer.a
8	./Player/UCloudMediaModule.h
8	./Player/UCloudMediaPlayback.h
8	./Player/UCloudMediaPlayer.h
8	./Player/UCloudPlayback.h
40	./Player
16	./Recorder/CameraServer.h
8	./Recorder/Filter/UCloudGLProgram.h
16	./Recorder/Filter/UCloudGPUImage.h
8	./Recorder/Filter/UCloudGPUImage3x3ConvolutionFilter.h
8	./Recorder/Filter/UCloudGPUImage3x3TextureSamplingFilter.h
8	./Recorder/Filter/UCloudGPUImageAdaptiveThresholdFilter.h
8	./Recorder/Filter/UCloudGPUImageAddBlendFilter.h
8	./Recorder/Filter/UCloudGPUImageAlphaBlendFilter.h
8	./Recorder/Filter/UCloudGPUImageAmatorkaFilter.h
8	./Recorder/Filter/UCloudGPUImageAverageColor.h
8	./Recorder/Filter/UCloudGPUImageAverageLuminanceThresholdFilter.h
8	./Recorder/Filter/UCloudGPUImageBeautyFilter.h
8	./Recorder/Filter/UCloudGPUImageBilateralFilter.h
8	./Recorder/Filter/UCloudGPUImageBoxBlurFilter.h
8	./Recorder/Filter/UCloudGPUImageBrightnessFilter.h
8	./Recorder/Filter/UCloudGPUImageBuffer.h
8	./Recorder/Filter/UCloudGPUImageBulgeDistortionFilter.h
8	./Recorder/Filter/UCloudGPUImageCannyEdgeDetectionFilter.h
8	./Recorder/Filter/UCloudGPUImageCGAColorspaceFilter.h
8	./Recorder/Filter/UCloudGPUImageChromaKeyBlendFilter.h
8	./Recorder/Filter/UCloudGPUImageChromaKeyFilter.h
8	./Recorder/Filter/UCloudGPUImageClosingFilter.h
8	./Recorder/Filter/UCloudGPUImageColorBlendFilter.h
8	./Recorder/Filter/UCloudGPUImageColorBurnBlendFilter.h
8	./Recorder/Filter/UCloudGPUImageColorConversion.h
8	./Recorder/Filter/UCloudGPUImageColorDodgeBlendFilter.h
8	./Recorder/Filter/UCloudGPUImageColorInvertFilter.h
8	./Recorder/Filter/UCloudGPUImageColorLocalBinaryPatternFilter.h
8	./Recorder/Filter/UCloudGPUImageColorMatrixFilter.h
8	./Recorder/Filter/UCloudGPUImageColorPackingFilter.h
8	./Recorder/Filter/UCloudGPUImageColourFASTFeatureDetector.h
8	./Recorder/Filter/UCloudGPUImageColourFASTSamplingOperation.h
8	./Recorder/Filter/UCloudGPUImageContext.h
8	./Recorder/Filter/UCloudGPUImageContrastFilter.h
8	./Recorder/Filter/UCloudGPUImageCropFilter.h
8	./Recorder/Filter/UCloudGPUImageCrosshairGenerator.h
8	./Recorder/Filter/UCloudGPUImageCrosshatchFilter.h
8	./Recorder/Filter/UCloudGPUImageDarkenBlendFilter.h
8	./Recorder/Filter/UCloudGPUImageDifferenceBlendFilter.h
8	./Recorder/Filter/UCloudGPUImageDilationFilter.h
8	./Recorder/Filter/UCloudGPUImageDirectionalNonMaximumSuppressionFilter.h
8	./Recorder/Filter/UCloudGPUImageDirectionalSobelEdgeDetectionFilter.h
8	./Recorder/Filter/UCloudGPUImageDissolveBlendFilter.h
8	./Recorder/Filter/UCloudGPUImageDivideBlendFilter.h
8	./Recorder/Filter/UCloudGPUImageEmbossFilter.h
8	./Recorder/Filter/UCloudGPUImageErosionFilter.h
8	./Recorder/Filter/UCloudGPUImageExclusionBlendFilter.h
8	./Recorder/Filter/UCloudGPUImageExposureFilter.h
8	./Recorder/Filter/UCloudGPUImageFalseColorFilter.h
8	./Recorder/Filter/UCloudGPUImageFASTCornerDetectionFilter.h
16	./Recorder/Filter/UCloudGPUImageFilter.h
8	./Recorder/Filter/UCloudGPUImageFilterGroup.h
8	./Recorder/Filter/UCloudGPUImageFilterPipeline.h
8	./Recorder/Filter/UCloudGPUImageFourInputFilter.h
8	./Recorder/Filter/UCloudGPUImageFramebuffer.h
8	./Recorder/Filter/UCloudGPUImageFramebufferCache.h
8	./Recorder/Filter/UCloudGPUImageGammaFilter.h
8	./Recorder/Filter/UCloudGPUImageGaussianBlurFilter.h
8	./Recorder/Filter/UCloudGPUImageGaussianBlurPositionFilter.h
8	./Recorder/Filter/UCloudGPUImageGaussianSelectiveBlurFilter.h
8	./Recorder/Filter/UCloudGPUImageGlassSphereFilter.h
8	./Recorder/Filter/UCloudGPUImageGrayscaleFilter.h
8	./Recorder/Filter/UCloudGPUImageHalftoneFilter.h
8	./Recorder/Filter/UCloudGPUImageHardLightBlendFilter.h
8	./Recorder/Filter/UCloudGPUImageHarrisCornerDetectionFilter.h
8	./Recorder/Filter/UCloudGPUImageHazeFilter.h
8	./Recorder/Filter/UCloudGPUImageHighlightShadowFilter.h
8	./Recorder/Filter/UCloudGPUImageHighPassFilter.h
8	./Recorder/Filter/UCloudGPUImageHistogramEqualizationFilter.h
8	./Recorder/Filter/UCloudGPUImageHistogramFilter.h
8	./Recorder/Filter/UCloudGPUImageHistogramGenerator.h
8	./Recorder/Filter/UCloudGPUImageHoughTransformLineDetector.h
8	./Recorder/Filter/UCloudGPUImageHSBFilter.h
8	./Recorder/Filter/UCloudGPUImageHueBlendFilter.h
8	./Recorder/Filter/UCloudGPUImageHueFilter.h
8	./Recorder/Filter/UCloudGPUImageiOSBlurFilter.h
8	./Recorder/Filter/UCloudGPUImageJFAVoronoiFilter.h
8	./Recorder/Filter/UCloudGPUImageKuwaharaFilter.h
8	./Recorder/Filter/UCloudGPUImageKuwaharaRadius3Filter.h
8	./Recorder/Filter/UCloudGPUImageLanczosResamplingFilter.h
8	./Recorder/Filter/UCloudGPUImageLaplacianFilter.h
8	./Recorder/Filter/UCloudGPUImageLevelsFilter.h
8	./Recorder/Filter/UCloudGPUImageLightenBlendFilter.h
8	./Recorder/Filter/UCloudGPUImageLinearBurnBlendFilter.h
8	./Recorder/Filter/UCloudGPUImageLineGenerator.h
8	./Recorder/Filter/UCloudGPUImageLocalBinaryPatternFilter.h
8	./Recorder/Filter/UCloudGPUImageLookupFilter.h
8	./Recorder/Filter/UCloudGPUImageLowPassFilter.h
8	./Recorder/Filter/UCloudGPUImageLuminanceRangeFilter.h
8	./Recorder/Filter/UCloudGPUImageLuminanceThresholdFilter.h
8	./Recorder/Filter/UCloudGPUImageLuminosity.h
8	./Recorder/Filter/UCloudGPUImageLuminosityBlendFilter.h
8	./Recorder/Filter/UCloudGPUImageMaskFilter.h
8	./Recorder/Filter/UCloudGPUImageMedianFilter.h
8	./Recorder/Filter/UCloudGPUImageMissEtikateFilter.h
8	./Recorder/Filter/UCloudGPUImageMonochromeFilter.h
8	./Recorder/Filter/UCloudGPUImageMosaicFilter.h
8	./Recorder/Filter/UCloudGPUImageMotionBlurFilter.h
8	./Recorder/Filter/UCloudGPUImageMotionDetector.h
8	./Recorder/Filter/UCloudGPUImageMovie.h
8	./Recorder/Filter/UCloudGPUImageMovieComposition.h
8	./Recorder/Filter/UCloudGPUImageMovieWriter.h
8	./Recorder/Filter/UCloudGPUImageMultiplyBlendFilter.h
8	./Recorder/Filter/UCloudGPUImageNobleCornerDetectionFilter.h
8	./Recorder/Filter/UCloudGPUImageNonMaximumSuppressionFilter.h
8	./Recorder/Filter/UCloudGPUImageNormalBlendFilter.h
8	./Recorder/Filter/UCloudGPUImageOpacityFilter.h
8	./Recorder/Filter/UCloudGPUImageOpeningFilter.h
16	./Recorder/Filter/UCloudGPUImageOutput.h
8	./Recorder/Filter/UCloudGPUImageOverlayBlendFilter.h
8	./Recorder/Filter/UCloudGPUImageParallelCoordinateLineTransformFilter.h
8	./Recorder/Filter/UCloudGPUImagePerlinNoiseFilter.h
8	./Recorder/Filter/UCloudGPUImagePicture+TextureSubimage.h
8	./Recorder/Filter/UCloudGPUImagePicture.h
8	./Recorder/Filter/UCloudGPUImagePinchDistortionFilter.h
8	./Recorder/Filter/UCloudGPUImagePixellateFilter.h
8	./Recorder/Filter/UCloudGPUImagePixellatePositionFilter.h
8	./Recorder/Filter/UCloudGPUImagePoissonBlendFilter.h
8	./Recorder/Filter/UCloudGPUImagePolarPixellateFilter.h
8	./Recorder/Filter/UCloudGPUImagePolkaDotFilter.h
8	./Recorder/Filter/UCloudGPUImagePosterizeFilter.h
8	./Recorder/Filter/UCloudGPUImagePrewittEdgeDetectionFilter.h
8	./Recorder/Filter/UCloudGPUImageRawDataInput.h
8	./Recorder/Filter/UCloudGPUImageRawDataOutput.h
8	./Recorder/Filter/UCloudGPUImageRGBClosingFilter.h
8	./Recorder/Filter/UCloudGPUImageRGBDilationFilter.h
8	./Recorder/Filter/UCloudGPUImageRGBErosionFilter.h
8	./Recorder/Filter/UCloudGPUImageRGBFilter.h
8	./Recorder/Filter/UCloudGPUImageRGBOpeningFilter.h
8	./Recorder/Filter/UCloudGPUImageSaturationBlendFilter.h
8	./Recorder/Filter/UCloudGPUImageSaturationFilter.h
8	./Recorder/Filter/UCloudGPUImageScreenBlendFilter.h
8	./Recorder/Filter/UCloudGPUImageSepiaFilter.h
8	./Recorder/Filter/UCloudGPUImageSharpenFilter.h
8	./Recorder/Filter/UCloudGPUImageShiTomasiFeatureDetectionFilter.h
8	./Recorder/Filter/UCloudGPUImageSingleComponentGaussianBlurFilter.h
8	./Recorder/Filter/UCloudGPUImageSketchFilter.h
8	./Recorder/Filter/UCloudGPUImageSmoothToonFilter.h
8	./Recorder/Filter/UCloudGPUImageSobelEdgeDetectionFilter.h
8	./Recorder/Filter/UCloudGPUImageSoftEleganceFilter.h
8	./Recorder/Filter/UCloudGPUImageSoftLightBlendFilter.h
8	./Recorder/Filter/UCloudGPUImageSolidColorGenerator.h
8	./Recorder/Filter/UCloudGPUImageSourceOverBlendFilter.h
8	./Recorder/Filter/UCloudGPUImageSphereRefractionFilter.h
8	./Recorder/Filter/UCloudGPUImageStillCamera.h
8	./Recorder/Filter/UCloudGPUImageStretchDistortionFilter.h
8	./Recorder/Filter/UCloudGPUImageSubtractBlendFilter.h
8	./Recorder/Filter/UCloudGPUImageSwirlFilter.h
8	./Recorder/Filter/UCloudGPUImageTextureInput.h
8	./Recorder/Filter/UCloudGPUImageTextureOutput.h
8	./Recorder/Filter/UCloudGPUImageThreeInputFilter.h
8	./Recorder/Filter/UCloudGPUImageThresholdEdgeDetectionFilter.h
8	./Recorder/Filter/UCloudGPUImageThresholdedNonMaximumSuppressionFilter.h
8	./Recorder/Filter/UCloudGPUImageThresholdSketchFilter.h
8	./Recorder/Filter/UCloudGPUImageTiltShiftFilter.h
8	./Recorder/Filter/UCloudGPUImageToneCurveFilter.h
8	./Recorder/Filter/UCloudGPUImageToonFilter.h
8	./Recorder/Filter/UCloudGPUImageTransformFilter.h
8	./Recorder/Filter/UCloudGPUImageTwoInputCrossTextureSamplingFilter.h
8	./Recorder/Filter/UCloudGPUImageTwoInputFilter.h
8	./Recorder/Filter/UCloudGPUImageTwoPassFilter.h
8	./Recorder/Filter/UCloudGPUImageTwoPassTextureSamplingFilter.h
8	./Recorder/Filter/UCloudGPUImageUIElement.h
8	./Recorder/Filter/UCloudGPUImageUnsharpMaskFilter.h
16	./Recorder/Filter/UCloudGPUImageVideoCamera.h
8	./Recorder/Filter/UCloudGPUImageView.h
8	./Recorder/Filter/UCloudGPUImageVignetteFilter.h
8	./Recorder/Filter/UCloudGPUImageVoronoiConsumerFilter.h
8	./Recorder/Filter/UCloudGPUImageWeakPixelInclusionFilter.h
8	./Recorder/Filter/UCloudGPUImageWhiteBalanceFilter.h
8	./Recorder/Filter/UCloudGPUImageXYDerivativeFilter.h
8	./Recorder/Filter/UCloudGPUImageZoomBlurFilter.h
1400	./Recorder/Filter
8	./Recorder/FilterManager.h
8	./Recorder/FilterManager.m
8	./Recorder/libUCloudMediaRecorder.a
8	./Recorder/NSString+UCloudCameraCode.h
1448	./Recorder
1504	.

**Comment by WangYng** [comment]
@lizilong1989 你们的工程有没有国内的git镜像?我去镜像网站clone试试

**Comment by lizilong1989** [comment]
@WangYng 你可以clone一份code，或者手动下载一下这两个lib，放到指定位置

https://github.com/easemob/livestream_demo_ios/raw/master/EaseMobLiveDemo/EaseMobLiveDemo/lib/Player/libUCloudMediaPlayer.a
https://github.com/easemob/livestream_demo_ios/raw/master/EaseMobLiveDemo/EaseMobLiveDemo/lib/Recorder/libUCloudMediaRecorder.a

**Comment by WangYng** [comment]
问题解决了
